### ISSUE TITLE
Incorrectly eaten value

### ISSUE THREAD

**Issue by tukoz** [syntax-tree/mdast#10]
Hope it's the right place to report. _Looks_ like #9 

```
DocToccing single file "browsers.md" for github.com.

==================

/usr/lib/node_modules/doctoc/node_modules/vfile/index.js:537
        throw err;
        ^
10:244: Incorrectly eaten value: please report this warning on http://git.io/vUYWz
```

Where `browsers.md` was edited after the initial TOC generation: file structure was changed;  level 1 document title was moved above the TOC, and its entry removed from the TOC.

**Comment by wooorm** [comment]
Yes, it does, thanks for reporting.

This problem arises because `doctoc` uses an old version of markdown-to-ast, which uses an old version of mdast (before the rename to remark, and many fixes).

@thlorenz you should update markdown-to-ast!

I’m closing this as this problem was (most likely) already fixed in remark.

**Comment by tukoz** [comment]
Thank you wooorm.
